### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Lak4CYUT**
Complete partually.

I don't understand what "pawns will not exceed inventory capacity" is means, whould somebody please help to explain it?

### CODE REVIEW

**Comment by catgirlfighter** [comment]
Hello. Inventory capacity means how much pawns can carry "normally" (how much they can put inside their backpack). In vanilla pawns mostly use it for caravans.

**Comment by catgirlfighter** [comment]
Should I cancel pull request for now?

**Comment by catgirlfighter** [comment]
Well, whatever. You probably just can make another one :)
Thanks!

**Comment by Lak4CYUT** [comment]
> Well, whatever. You probably just can make another one :) Thanks!

XD, of course I can make another one. It is nice to see you come back to dev. MOD.

**Comment by Lak4CYUT** [comment]
> Hello. Inventory capacity means how much pawns can carry "normally" (how much they can put inside their backpack). In vanilla pawns mostly use it for caravans.

Wow, so it means when people use this MOD, pawns have a chance to carry items over then "Inventory capacity"?

**Comment by catgirlfighter** [comment]
Used to. That was always a standard behavior in CommonSense. Recipes that have unreasonable amount of ingredients are rare even among mods, so normally you wouldn't even notice that pawns carry a lot more than they normally would be able. With this option pawns will not do it anymore.

**Pull request merged**
