### PR TITLE
fix for outside-of-inventory requirement of StartCarryThing()

### PR DESCRIPTION
**Pull request by CodeOptimist**
Received this save game today with an interesting "10 jobs in one tick" error. Narrowed it down.
https://www.twitch.tv/videos/1650380241
Too bad the audio is messed-up in these final 10 minutes, I had to change some things and forgot to fix the webcam sync & pause game. 😂

Got really lucky that Smart Medicine was installed and appeared in the toils list when I would disable the "pick up ingredients" option in CS. Made me go, "Huh? Nah probably not related." Boy was I wrong. Turns out AlexTD ran into this and had actually [fixed it for SmartMedicine](https://github.com/alextd/RimWorld-SmartMedicine/blob/84e7ac3e84a7f68dd7c7ed493296c0f9d7103f8e/Source/InventorySurgery.cs#L72)!

Here's the save I used to repro. [DropTargetThingIfInInventory.zip](https://github.com/catgirlfighter/RimWorld_CommonSense/files/9994412/DropTargetThingIfInInventory.zip)
Approximately 30 mods. Wait for _Buck_ to reach _Electric smithy_ at center screen.

As per usual, change/reformat/rewrite/whatever-you'd-like before merging. Double check my work, etc.
I _think_ this fix makes sense but I only checked this one case.

I changed `actor.inventory.Contains(thing)` from SmartMedicine to the `thing.ParentHolder == actor.inventory` from CommonSense, which seems okay? And using `TargetIndex.B`.

### CODE REVIEW

**Comment by catgirlfighter** [comment]
Hey, thank you so much for finally pin-pointing the issue! I see the point of a fix, not sure I gonna keep it that way tho. I didn't play with any of hauling mods since 1.4 so I had no opportunity to catch the problem.

**Comment by catgirlfighter** [comment]
Eh, it's still a problem when option to haul items using inventory is disabled, because it reverts to basic scenario. Also your variant doesn't take into account that item could be in SOMEBODY ELSE inventory (which is easy to fix though). I've got the problem asap when my fabricator mech tried to take unfinished item from my crafter's inventory.

**Comment by catgirlfighter** [comment]
I'll sleep on it for some time. I need to figure out a better way to fix this.

**Comment by CodeOptimist** [comment]
Great catches!

**Comment by catgirlfighter** [comment]
Ok, did final strokes. Hope it works.

**Pull request merged**
